### ISSUE TITLE
yaws deps

### ISSUE THREAD

**Issue by stuart-thackray** [nitrogen/simple_bridge#48]
Hi Jesse,

Just FYI for erlang 18 we need yaws 2.0 I don't know the exact changes required. The one would be to update simple_bridge/rebar_deps/yaws.deps but not getting it to compile/make.

==> yaws (compile)
yaws.erl:13: can't find include file "yaws_appdeps.hrl"
yaws.erl:221: undefined macro 'YAWS_APPDEPS'
yaws.erl:175: function start_app_deps/0 undefined
yaws.erl:195: function start_app_deps/0 undefined

**Comment by stuart-thackray** [comment]
I am not sure if it just an issue with yaws and Mac as yaws says to install from repo rather than using the configure script.

but for erlang 18 yaws 2.0 is required.

**Comment by choptastic** [comment]
Thanks Stuart!

I was not aware of this. I'll have to find out about this.

-Jesse

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by stuart-thackray** [comment]
I am closing this and will create a PR for using yaws 2.0.2 which builds as expected.

**Comment by choptastic** [comment]
Oh sweet!
