### ISSUE TITLE
"undefined" instead of undefined result when param not found in request

### ISSUE THREAD

**Issue by brigadier** [nitrogen/simple_bridge#56]
this code

```
find_param(Param, Default, ParamList) when is_binary(Param) ->
    case lists:keyfind(Param, 1, ParamList) of
        {_, Val} -> Val;
        false -> Default
    end;
find_param(Param, Default, ParamList) when is_atom(Param); is_list(Param) ->
    Param1 = simple_bridge_util:to_binary(Param),
    simple_bridge_util:to_list(find_param(Param1, Default, ParamList)).
```

makes simple_bridge return "undefined" (list, not atom) for not found params when the key is a list or atom.

**Comment by choptastic** [comment]
Thanks, I should have time to whip up a fix for this over the weekend, otherwise I'm open to a pull request, if you feel so inclined :)

**Comment by brigadier** [comment]
https://github.com/nitrogen/simple_bridge/pull/57

But I'm not sure if it is enough
