### ISSUE TITLE
About sendfile funs

### ISSUE THREAD

**Issue by essen** [nitrogen/simple_bridge#68]
Sorry to pollute your ticket tracker but I can't seem to be able to send you an email, getting a DNS related error? Anyway here's what I wanted to say:

This area of Cowboy was modified because of HTTP/2. Cowboy can no longer give direct socket access and therefore the funs were removed. Instead, sendfile is now a tuple that can be given anywhere a body or body segment is expected (so there can be more than one).

**Comment by choptastic** [comment]
Thanks for the clarification, Loic! Appreciate the explanation. That makes
sense with respect to the http2.

I'll work in a workaround.

Cheers, man!

I'm guessing the DNS error had to do with Google groups.  It kinda sucks.

-Jesse

**Comment by essen** [comment]
Cheers.
