### ISSUE TITLE
Incorrect processing  of post requests with abnormal content type

### ISSUE THREAD

**Issue by meike-hecker** [nitrogen/simple_bridge#69]
It seems simple bridge tries to parse the body as "application/x-www-urlencoded" when ever a request is not multipart. There are plenty of content-types and use cases where this is not valid.
At least in the case of cowboy this behaviour leads to a crash.
I stumbled about it while building a rest api, that accepts "application/my-app-binary" without urlencoding the content.

**Comment by meike-hecker** [comment]
This is a bug in simple bridge. It is incorrect to parse content body as urlencoded when it isn't urlencoded.

**Comment by choptastic** [comment]
I understand. I've merged your PR, which is why I closed this issue.

**Comment by meike-hecker** [comment]
Yes  sorry, just realized...
